include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  errors:
    prefer_single_quotes: ignore
    constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    invalid_use_of_protected_member: ignore
    depend_on_referenced_packages: ignore
    file_names: ignore

linter:
  rules:
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    unnecessary_const: true
    prefer_const_constructors: true
    sort_constructors_first: true
    prefer_relative_imports: false
    prefer_single_quotes: true

dart_code_metrics:
  extends:
    - recommended
  rules:
    avoid-inferrable-type-arguments: false
    avoid-undisposed-instances: false
    avoid-shadowing: false
